import type { LessonWithChallenges } from "./types";

const MOCK_CREATED_AT = new Date("2026-03-24T00:00:00.000Z").toISOString();

export const translationAssemblyMockLesson: LessonWithChallenges = {
	id: -2,
	unitId: -1,
	title: "Translation Assembly Test",
	order: 0,
	createdAt: MOCK_CREATED_AT,
	challenges: [
		{
			id: -201,
			lessonId: -2,
			type: "TRANSLATE",
			question: "她正在读一本书。",
			sentence: null,
			translation: "She is reading a book.",
			sourceLang: "zh",
			targetLang: "en",
			audioUrl: null,
			order: 0,
			createdAt: MOCK_CREATED_AT,
			options: [],
			tokens: [],
		},
		{
			id: -202,
			lessonId: -2,
			type: "TRANSLATE",
			question: "我们明天去公园。",
			sentence: null,
			translation: "We will go to the park tomorrow.",
			sourceLang: "zh",
			targetLang: "en",
			audioUrl: null,
			order: 1,
			createdAt: MOCK_CREATED_AT,
			options: [],
			tokens: [],
		},
	],
};

export const dictationAssemblyMockLesson: LessonWithChallenges = {
	id: -1,
	unitId: -1,
	title: "Dictation Assembly Test",
	order: 0,
	createdAt: MOCK_CREATED_AT,
	challenges: [
		{
			id: -101,
			lessonId: -1,
			type: "DICTATION_ASSEMBLY",
			question: "She is reading a book.",
			sentence: null,
			translation: "她正在读一本书。",
			sourceLang: "en",
			targetLang: "zh",
			audioUrl: null,
			order: 0,
			createdAt: MOCK_CREATED_AT,
			options: [],
			tokens: [],
		},
	],
};

export const singleSelectMockLesson: LessonWithChallenges = {
	id: -3,
	unitId: -1,
	title: "Single Select Test",
	order: 0,
	createdAt: MOCK_CREATED_AT,
	challenges: [
		{
			id: -301,
			lessonId: -3,
			type: "SINGLE_SELECT",
			question: "Which planet is known as the Red Planet?",
			sentence: null,
			translation: "Mars is called the Red Planet because of its reddish appearance.",
			sourceLang: "en",
			targetLang: "en",
			audioUrl: null,
			order: 0,
			createdAt: MOCK_CREATED_AT,
			options: [
				{
					id: -3001,
					challengeId: -301,
					text: "Venus",
					isCorrect: false,
					audioUrl: null,
					order: 0,
				},
				{
					id: -3002,
					challengeId: -301,
					text: "Mars",
					isCorrect: true,
					audioUrl: null,
					order: 1,
				},
				{
					id: -3003,
					challengeId: -301,
					text: "Jupiter",
					isCorrect: false,
					audioUrl: null,
					order: 2,
				},
				{
					id: -3004,
					challengeId: -301,
					text: "Mercury",
					isCorrect: false,
					audioUrl: null,
					order: 3,
				},
			],
			tokens: [],
		},
		{
			id: -302,
			lessonId: -3,
			type: "SINGLE_SELECT",
			question: "What is the capital of Japan?",
			sentence: null,
			translation: "Tokyo is the capital city of Japan.",
			sourceLang: "en",
			targetLang: "en",
			audioUrl: null,
			order: 1,
			createdAt: MOCK_CREATED_AT,
			options: [
				{
					id: -3011,
					challengeId: -302,
					text: "Seoul",
					isCorrect: false,
					audioUrl: null,
					order: 0,
				},
				{
					id: -3012,
					challengeId: -302,
					text: "Kyoto",
					isCorrect: false,
					audioUrl: null,
					order: 1,
				},
				{
					id: -3013,
					challengeId: -302,
					text: "Tokyo",
					isCorrect: true,
					audioUrl: null,
					order: 2,
				},
				{
					id: -3014,
					challengeId: -302,
					text: "Osaka",
					isCorrect: false,
					audioUrl: null,
					order: 3,
				},
			],
			tokens: [],
		},
		{
			id: -303,
			lessonId: -3,
			type: "SINGLE_SELECT",
			question: "Which CSS property controls the text color?",
			sentence: null,
			translation: "The `color` property sets the color of text.",
			sourceLang: "en",
			targetLang: "en",
			audioUrl: null,
			order: 2,
			createdAt: MOCK_CREATED_AT,
			options: [
				{
					id: -3021,
					challengeId: -303,
					text: "background-color",
					isCorrect: false,
					audioUrl: null,
					order: 0,
				},
				{
					id: -3022,
					challengeId: -303,
					text: "font-weight",
					isCorrect: false,
					audioUrl: null,
					order: 1,
				},
				{
					id: -3023,
					challengeId: -303,
					text: "color",
					isCorrect: true,
					audioUrl: null,
					order: 2,
				},
				{
					id: -3024,
					challengeId: -303,
					text: "text-align",
					isCorrect: false,
					audioUrl: null,
					order: 3,
				},
			],
			tokens: [],
		},
	],
};

export const selectTranslationMockLesson: LessonWithChallenges = {
	id: -4,
	unitId: -1,
	title: "Select Translation Test",
	order: 0,
	createdAt: MOCK_CREATED_AT,
	challenges: [
		{
			id: -401,
			lessonId: -4,
			type: "SELECT_TRANSLATION",
			question: "library",
			sentence: null,
			translation: "图书馆",
			sourceLang: "en",
			targetLang: "zh",
			audioUrl: null,
			order: 0,
			createdAt: MOCK_CREATED_AT,
			options: [
				{
					id: -4001,
					challengeId: -401,
					text: "教室",
					isCorrect: false,
					audioUrl: null,
					order: 0,
				},
				{
					id: -4002,
					challengeId: -401,
					text: "医院",
					isCorrect: false,
					audioUrl: null,
					order: 1,
				},
				{
					id: -4003,
					challengeId: -401,
					text: "图书馆",
					isCorrect: true,
					audioUrl: null,
					order: 2,
				},
				{
					id: -4004,
					challengeId: -401,
					text: "餐厅",
					isCorrect: false,
					audioUrl: null,
					order: 3,
				},
			],
			tokens: [],
		},
		{
			id: -404,
			lessonId: -4,
			type: "SELECT_TRANSLATION",
			question: "老师",
			sentence: null,
			translation: "teacher",
			sourceLang: "zh",
			targetLang: "en",
			audioUrl: null,
			order: 1,
			createdAt: MOCK_CREATED_AT,
			options: [
				{
					id: -4031,
					challengeId: -404,
					text: "student",
					isCorrect: false,
					audioUrl: null,
					order: 0,
				},
				{
					id: -4032,
					challengeId: -404,
					text: "doctor",
					isCorrect: false,
					audioUrl: null,
					order: 1,
				},
				{
					id: -4033,
					challengeId: -404,
					text: "teacher",
					isCorrect: true,
					audioUrl: null,
					order: 2,
				},
				{
					id: -4034,
					challengeId: -404,
					text: "driver",
					isCorrect: false,
					audioUrl: null,
					order: 3,
				},
			],
			tokens: [],
		},
	],
};
